version: "3.8"

services:
  mysql-user:
    image: mysql:8
    container_name: mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: userdb
    ports:
      - "3307:3306"
    volumes:
      - ./docker/userdb.sql:/docker-entrypoint-initdb.d/userdb.sql
    networks:
      - bookstore-net

  mysql-book:
    image: mysql:8
    container_name: mysql-book
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: bookdb
    ports:
      - "3308:3306"
    volumes:
      - ./docker/bookdb.sql:/docker-entrypoint-initdb.d/bookdb.sql
    networks:
      - bookstore-net

  mysql-order:
    image: mysql:8
    container_name: mysql-order
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: orderdb
    ports:
      - "3309:3306"
    volumes:
      - ./docker/orderdb.sql:/docker-entrypoint-initdb.d/orderdb.sql
    networks:
      - bookstore-net

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "4000:4000"
    depends_on:
      - mysql-user
    environment:
      - DB_HOST=mysql-user
      - DB_USER=root
      - DB_PASSWORD=pass
      - DB_NAME=userdb
      - HOST=0.0.0.0
      - PORT=4000
    networks:
      - bookstore-net

  book-service:
    build: ./book-service
    container_name: book-service
    ports:
      - "4001:4001"
    depends_on:
      - mysql-book
    environment:
      - DB_HOST=mysql-book
      - DB_USER=root
      - DB_PASSWORD=pass
      - DB_NAME=bookdb
      - HOST=0.0.0.0
      - PORT=4001
    networks:
      - bookstore-net

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "4002:4002"
    depends_on:
      - mysql-order
    environment:
      - DB_HOST=mysql-order
      - DB_USER=root
      - DB_PASSWORD=pass
      - DB_NAME=orderdb
      - HOST=0.0.0.0
      - PORT=4002
    networks:
      - bookstore-net

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    depends_on:
      - user-service
      - book-service
      - order-service
    networks:
      - bookstore-net

networks:
  bookstore-net:
    driver: bridge

